from . import admin
from . import start
from . import back
from . import check_test_file
from . import login
from . import home
from . import help
from . import set_lang
from . import send_test
from . import ready